// Generated automatically by nearley, version 2.20.1
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "mad", "symbols": ["expr"]},
    {"name": "mad", "symbols": ["expr", "nl", "mad"], "postprocess": ([e,,m]) => [e, ...m]},
    {"name": "expr", "symbols": ["e"], "postprocess": id},
    {"name": "expr", "symbols": ["h1"], "postprocess": id},
    {"name": "expr", "symbols": ["h2"], "postprocess": id},
    {"name": "expr", "symbols": ["h3"], "postprocess": id},
    {"name": "expr", "symbols": ["h4"], "postprocess": id},
    {"name": "expr", "symbols": ["h5"], "postprocess": id},
    {"name": "expr", "symbols": ["h6"], "postprocess": id},
    {"name": "expr", "symbols": ["p"], "postprocess": id},
    {"name": "expr", "symbols": ["quote"], "postprocess": id},
    {"name": "expr", "symbols": ["code"], "postprocess": id},
    {"name": "expr", "symbols": ["comp"], "postprocess": id},
    {"name": "expr", "symbols": ["attr"], "postprocess": id},
    {"name": "h1$macrocall$2", "symbols": [{"literal":"#"}]},
    {"name": "h1$macrocall$1$ebnf$1$subexpression$1", "symbols": [/[^#\n\r]/, "line"], "postprocess": ([c,l]) => `${c}${l}`.trim()},
    {"name": "h1$macrocall$1$ebnf$1", "symbols": ["h1$macrocall$1$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "h1$macrocall$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "h1$macrocall$1", "symbols": ["e", "h1$macrocall$2", "h1$macrocall$1$ebnf$1"], "postprocess": ([,,l]) => l || ''},
    {"name": "h1", "symbols": ["h1$macrocall$1"], "postprocess": ([l])        => ({t:"h1",    v:l                })},
    {"name": "h2$macrocall$2$string$1", "symbols": [{"literal":"#"}, {"literal":"#"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "h2$macrocall$2", "symbols": ["h2$macrocall$2$string$1"]},
    {"name": "h2$macrocall$1$ebnf$1$subexpression$1", "symbols": [/[^#\n\r]/, "line"], "postprocess": ([c,l]) => `${c}${l}`.trim()},
    {"name": "h2$macrocall$1$ebnf$1", "symbols": ["h2$macrocall$1$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "h2$macrocall$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "h2$macrocall$1", "symbols": ["e", "h2$macrocall$2", "h2$macrocall$1$ebnf$1"], "postprocess": ([,,l]) => l || ''},
    {"name": "h2", "symbols": ["h2$macrocall$1"], "postprocess": ([l])        => ({t:"h2",    v:l                })},
    {"name": "h3$macrocall$2$string$1", "symbols": [{"literal":"#"}, {"literal":"#"}, {"literal":"#"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "h3$macrocall$2", "symbols": ["h3$macrocall$2$string$1"]},
    {"name": "h3$macrocall$1$ebnf$1$subexpression$1", "symbols": [/[^#\n\r]/, "line"], "postprocess": ([c,l]) => `${c}${l}`.trim()},
    {"name": "h3$macrocall$1$ebnf$1", "symbols": ["h3$macrocall$1$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "h3$macrocall$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "h3$macrocall$1", "symbols": ["e", "h3$macrocall$2", "h3$macrocall$1$ebnf$1"], "postprocess": ([,,l]) => l || ''},
    {"name": "h3", "symbols": ["h3$macrocall$1"], "postprocess": ([l])        => ({t:"h3",    v:l                })},
    {"name": "h4$macrocall$2$string$1", "symbols": [{"literal":"#"}, {"literal":"#"}, {"literal":"#"}, {"literal":"#"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "h4$macrocall$2", "symbols": ["h4$macrocall$2$string$1"]},
    {"name": "h4$macrocall$1$ebnf$1$subexpression$1", "symbols": [/[^#\n\r]/, "line"], "postprocess": ([c,l]) => `${c}${l}`.trim()},
    {"name": "h4$macrocall$1$ebnf$1", "symbols": ["h4$macrocall$1$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "h4$macrocall$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "h4$macrocall$1", "symbols": ["e", "h4$macrocall$2", "h4$macrocall$1$ebnf$1"], "postprocess": ([,,l]) => l || ''},
    {"name": "h4", "symbols": ["h4$macrocall$1"], "postprocess": ([l])        => ({t:"h4",    v:l                })},
    {"name": "h5$macrocall$2$string$1", "symbols": [{"literal":"#"}, {"literal":"#"}, {"literal":"#"}, {"literal":"#"}, {"literal":"#"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "h5$macrocall$2", "symbols": ["h5$macrocall$2$string$1"]},
    {"name": "h5$macrocall$1$ebnf$1$subexpression$1", "symbols": [/[^#\n\r]/, "line"], "postprocess": ([c,l]) => `${c}${l}`.trim()},
    {"name": "h5$macrocall$1$ebnf$1", "symbols": ["h5$macrocall$1$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "h5$macrocall$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "h5$macrocall$1", "symbols": ["e", "h5$macrocall$2", "h5$macrocall$1$ebnf$1"], "postprocess": ([,,l]) => l || ''},
    {"name": "h5", "symbols": ["h5$macrocall$1"], "postprocess": ([l])        => ({t:"h5",    v:l                })},
    {"name": "h6$macrocall$2$string$1", "symbols": [{"literal":"#"}, {"literal":"#"}, {"literal":"#"}, {"literal":"#"}, {"literal":"#"}, {"literal":"#"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "h6$macrocall$2", "symbols": ["h6$macrocall$2$string$1"]},
    {"name": "h6$macrocall$1$ebnf$1$subexpression$1", "symbols": [/[^#\n\r]/, "line"], "postprocess": ([c,l]) => `${c}${l}`.trim()},
    {"name": "h6$macrocall$1$ebnf$1", "symbols": ["h6$macrocall$1$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "h6$macrocall$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "h6$macrocall$1", "symbols": ["e", "h6$macrocall$2", "h6$macrocall$1$ebnf$1"], "postprocess": ([,,l]) => l || ''},
    {"name": "h6", "symbols": ["h6$macrocall$1"], "postprocess": ([l])        => ({t:"h6",    v:l                })},
    {"name": "quote", "symbols": ["e", {"literal":">"}, "line"], "postprocess": ([,,l])      => ({t:'quote', v:l.trim()         })},
    {"name": "code", "symbols": ["e", {"literal":"`"}, "line"], "postprocess": ([,,l])      => ({t:'code',  v:l                })},
    {"name": "p", "symbols": ["e", /[^#>`\s:{]/, "line"], "postprocess": ([,c,l])     => ({t:'p',     v:`${c}${l}`.trim()})},
    {"name": "comp", "symbols": ["e", "tag"], "postprocess": ([,t])          => ({t:"comp",  v:t, a:[] })},
    {"name": "comp", "symbols": ["e", "tag", "_", {"literal":"{"}, "_", "args", "_", {"literal":"}"}], "postprocess": ([,t,,,,as])    => ({t:"comp",  v:t, a:as })},
    {"name": "args$ebnf$1", "symbols": [{"literal":","}], "postprocess": id},
    {"name": "args$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "args", "symbols": ["arg", "_", "args$ebnf$1"], "postprocess": ([arg])         => [arg]},
    {"name": "args", "symbols": ["arg", "_", {"literal":","}, "_", "args"], "postprocess": ([arg,,,,args]) => [arg, ...args]},
    {"name": "arg", "symbols": ["word", "_", {"literal":":"}, "_", "anum"], "postprocess": ([n,,,,v])      => ({t:"named-arg",   n, v})},
    {"name": "arg", "symbols": ["word", "_", {"literal":":"}, "_", {"literal":"{"}, "mad", {"literal":"}"}], "postprocess": ([n,,,,,c])     => ({t:"content-arg", n, c})},
    {"name": "attr", "symbols": ["e", {"literal":"{"}, "_", "attrs", "_", {"literal":"}"}], "postprocess": ([,,,a])         => ({t:'attr',  v:a      })},
    {"name": "attrs", "symbols": ["props"], "postprocess": id},
    {"name": "attrs", "symbols": ["id"], "postprocess": id},
    {"name": "attrs", "symbols": ["props", "__", "id"], "postprocess": ([as,,id])       => [...as, id]},
    {"name": "attrs", "symbols": ["id", "__", "props"], "postprocess": ([id,,as])       => [id, ...as]},
    {"name": "attrs", "symbols": ["props", "__", "id", "__", "props"], "postprocess": ([as1,,id,,as2]) => [...as1, id, ...as2]},
    {"name": "props", "symbols": ["prop"]},
    {"name": "props", "symbols": ["prop", "__", "props"], "postprocess": ([attr,,props])  => [attr, ...props]},
    {"name": "prop", "symbols": ["boolAtt"], "postprocess": id},
    {"name": "prop", "symbols": ["namedAttr"], "postprocess": id},
    {"name": "prop", "symbols": ["class"], "postprocess": id},
    {"name": "boolAtt", "symbols": ["word"], "postprocess": ([v])            => ({t:"bool-attr",  v   })},
    {"name": "namedAttr", "symbols": ["word", "_", {"literal":"="}, "_", "anum"], "postprocess": ([n,,,,v])       => ({t:"named-attr", n, v})},
    {"name": "class", "symbols": [{"literal":"."}, "word"], "postprocess": ([,v])           => ({t:"class-attr", v   })},
    {"name": "id", "symbols": [{"literal":"#"}, "word"], "postprocess": ([,v])           => ({t:"id-attr",    v   })},
    {"name": "_$ebnf$1", "symbols": []},
    {"name": "_$ebnf$1", "symbols": ["_$ebnf$1", /[\s]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "_", "symbols": ["_$ebnf$1"], "postprocess": d => null},
    {"name": "__$ebnf$1", "symbols": [/[\s]/]},
    {"name": "__$ebnf$1", "symbols": ["__$ebnf$1", /[\s]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "__", "symbols": ["__$ebnf$1"], "postprocess": d => null},
    {"name": "e$ebnf$1", "symbols": []},
    {"name": "e$ebnf$1", "symbols": ["e$ebnf$1", /[^\S\r\n]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "e", "symbols": ["e$ebnf$1"], "postprocess": () => ({t:"empty"})},
    {"name": "q", "symbols": [{"literal":"'"}]},
    {"name": "q", "symbols": [{"literal":"\""}], "postprocess": d => null},
    {"name": "word$ebnf$1", "symbols": [/[\w-]/]},
    {"name": "word$ebnf$1", "symbols": ["word$ebnf$1", /[\w-]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "word", "symbols": ["word$ebnf$1"], "postprocess": ([d]) => d.join('')},
    {"name": "anum", "symbols": ["string"], "postprocess": id},
    {"name": "anum", "symbols": ["number"], "postprocess": id},
    {"name": "string$ebnf$1", "symbols": []},
    {"name": "string$ebnf$1", "symbols": ["string$ebnf$1", /[\w\s.]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "string", "symbols": ["q", "string$ebnf$1", "q"], "postprocess": ([,s]) => s.join('')},
    {"name": "number$ebnf$1", "symbols": [/[\d]/]},
    {"name": "number$ebnf$1", "symbols": ["number$ebnf$1", /[\d]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "number", "symbols": ["number$ebnf$1"], "postprocess": ([d]) => d.join('')},
    {"name": "number$ebnf$2", "symbols": [/[\d]/]},
    {"name": "number$ebnf$2", "symbols": ["number$ebnf$2", /[\d]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "number$ebnf$3", "symbols": [/[\d]/]},
    {"name": "number$ebnf$3", "symbols": ["number$ebnf$3", /[\d]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "number", "symbols": ["number$ebnf$2", {"literal":"."}, "number$ebnf$3"], "postprocess": ([d]) => d.join('')},
    {"name": "nl", "symbols": [/[\n\r]/], "postprocess": d => null},
    {"name": "line$ebnf$1", "symbols": []},
    {"name": "line$ebnf$1", "symbols": ["line$ebnf$1", /[^\n\r]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "line", "symbols": ["line$ebnf$1"], "postprocess": ([d]) => d.join('')},
    {"name": "tag", "symbols": [{"literal":":"}, "word", {"literal":"-"}, "word"], "postprocess": ([,w1,d,w2]) => w1 + d + w2}
]
  , ParserStart: "mad"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
